# Generated by Django 5.0.3 on 2026-04-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0006_operacion_detalle_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID del encabezado original del correo', max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, default='Sin asunto', max_length=500)),
                ('sender_address', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('recipient_address', models.TextField(help_text='Separados por coma si hay varios')),
                ('cc_address', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField()),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('inbound', 'Recibido'), ('outbound', 'Enviado')], default='inbound', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_adjuntos', to='operaciones.operacion')),
            ],
            options={
                'verbose_name': 'Mensaje de Correo',
                'verbose_name_plural': 'Mensajes de Correo',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emails/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correos.emailmessage')),
            ],
        ),
    ]
