# Generated by Django 5.0.3 on 2026-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo', models.TextField()),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
                'ordering': ['titulo'],
            },
        ),
    ]
