# Generated by Django 5.0.3 on 2026-04-06 14:54

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='contables_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_contables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='operadores_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='operarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_operario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('solicitada', 'Solicitada'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Borrador)'), ('presupuestada', 'Presupuestada / Confirmada'), ('en_produccion', 'En Producción / En Coordinación'), ('lista_para_envio', 'Lista para Envío'), ('remitada', 'Remitada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=50, protected=True),
        ),
    ]
