# Generated by Django 5.0.3 on 2026-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacion_contables_asignados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='client_confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='order_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='packing_list_file',
            field=models.FileField(blank=True, null=True, upload_to='packing_lists/'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='rancho_file',
            field=models.FileField(blank=True, null=True, upload_to='ranchos/'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='remito_file',
            field=models.FileField(blank=True, null=True, upload_to='remitos/'),
        ),
    ]
