# Generated by Django 5.0.3 on 2026-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_operacion_client_confirmed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='stock_consumido',
            field=models.BooleanField(default=False),
        ),
    ]
