# Generated by Django 5.0.3 on 2026-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_operacion_stock_consumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='aprobacion_requerida_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('productos', 'Productos'), ('quimicos', 'Químicos'), ('servicios', 'Servicios')], default='productos', max_length=20),
        ),
    ]
