# Generated by Django 5.0.3 on 2026-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_operacion_aprobacion_requerida_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='detalle_servicio',
            field=models.TextField(blank=True, help_text='Descripción detallada para operaciones de tipo Servicio.', null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='forma_cotizacion_servicio',
            field=models.CharField(blank=True, choices=[('hora_hombre', 'Hora Hombre'), ('dias', 'Días'), ('lumpsum', 'Lumpsum (Suma Global)')], max_length=20, null=True),
        ),
    ]
