# Generated by Django 5.0.3 on 2026-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_operacion_detalle_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='estado_revision',
            field=models.CharField(choices=[('none', 'Ninguna'), ('pending', 'Pendiente de Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='operacion',
            name='mensaje_revision',
            field=models.TextField(blank=True, help_text='Comentarios del operador (al solicitar) o del owner (al aprobar/rechazar).', null=True),
        ),
    ]
