# Generated by Django 5.0.3 on 2026-04-21 23:32

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_operacion_estado_revision_operacion_mensaje_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='texto_pedido',
            field=models.TextField(blank=True, help_text='Contenido original del e-mail o pedido del cliente.', null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('solicitada', 'Generada / Pendiente Packing'), ('armado_packing', 'En Gestión (Armado del Packing List)'), ('en_aduana', 'En Aduana (Esperando Rancho)'), ('lista_para_envio', 'Logística (Despacho y Remito)'), ('remitada', 'Entregada en sitio'), ('entregada', 'Completada / Cerrada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=50, protected=True),
        ),
    ]
