# Generated by Django 5.0.3 on 2026-04-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_agendaevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
