# Generated by Django 5.0.3 on 2026-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_agendaevent_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre identificatorio de la operación', max_length=200, null=True),
        ),
    ]
