# Generated by Django 5.0.3 on 2026-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_operacion_nombre'),
        ('usuarios', '0004_personalplantel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='operarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_asociadas', to='usuarios.personalplantel'),
        ),
    ]
