# Generated by Django 5.0.3 on 2026-05-04 19:42

from django.db import migrations, models


def clean_orphans(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM operaciones_operacion_operarios_asignados")

class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_operacion_nombre'),
        ('usuarios', '0004_personalplantel'),
    ]

    operations = [
        migrations.RunPython(clean_orphans, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='operacion',
            name='operarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_asociadas', to='usuarios.personalplantel'),
        ),
    ]
