# Generated by Django 5.0.3 on 2026-05-06 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_operacion_operarios_asignados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='operarios_usuarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_como_operario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='subtipo_servicio',
            field=models.CharField(blank=True, help_text='Categoría específica del servicio (Mecanica, Electricidad, etc.)', max_length=100, null=True),
        ),
    ]
