# Generated by Django 5.0.3 on 2026-05-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_operacion_operarios_usuarios_asignados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('productos', 'Productos'), ('quimicos', 'Químicos'), ('servicios', 'Servicios'), ('otros', 'Otros')], default='productos', max_length=20),
        ),
    ]
