# Generated by Django 5.0.3 on 2026-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_alter_operacion_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='imo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
