# Generated by Django 5.0.3 on 2026-05-18 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_alter_ship_flag_alter_ship_imo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('delivery_note', 'Delivery Note'), ('factura_proveedor', 'Factura a proveedor'), ('habilitacion_aduanera', 'Habilitación aduanera'), ('otros', 'Otros')], max_length=30)),
                ('nombre_personalizado', models.CharField(blank=True, help_text="Usar si tipo es 'Otros'", max_length=200, null=True)),
                ('archivo', models.FileField(upload_to='operaciones/documentos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_adjuntos', to='operaciones.operacion')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
