# Generated by Django 5.0.3 on 2026-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_plantel_estatico'),
        ('operaciones', '0016_documentoadjunto'),
    ]

    operations = [
    ]
