# Generated by Django 5.0.3 on 2026-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_merge_0015_plantel_estatico_0016_documentoadjunto'),
        ('usuarios', '0004_personalplantel'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='operarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='operaciones_como_plantel', to='usuarios.personalplantel'),
        ),
    ]
