# Generated by Django 5.0.3 on 2026-05-21 17:30

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_operacion_operarios_asignados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadjunto',
            name='tipo',
            field=models.CharField(choices=[('delivery_note', 'Preparación'), ('factura_proveedor', 'Factura a proveedor'), ('habilitacion_aduanera', 'Habilitación aduanera'), ('otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('solicitada', 'Preparación'), ('armado_packing', 'En Gestión (Armado del Packing List)'), ('en_aduana', 'En Aduana (Esperando Rancho)'), ('lista_para_envio', 'Logística (Despacho y Remito)'), ('remitada', 'Entregada en sitio'), ('entregada', 'Completada / Cerrada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=50, protected=True),
        ),
    ]
