# Generated by Django 5.0.3 on 2026-06-02 16:18

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0019_alter_documentoadjunto_tipo_alter_operacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadjunto',
            name='tipo',
            field=models.CharField(choices=[('delivery_note', 'Preparación'), ('factura_proveedor', 'Factura a proveedor'), ('habilitacion_aduanera', 'Habilitación aduanera'), ('cotizacion_servicio', 'Cotización de Servicio'), ('permiso_pna', 'Permiso PNA'), ('solicitud_particular', 'Solicitud Particular'), ('reporte_servicio', 'Reporte de Servicio'), ('otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('solicitada', 'Preparación'), ('armado_packing', 'En Gestión (Armado del Packing List)'), ('en_aduana', 'En Aduana (Esperando Rancho)'), ('lista_para_envio', 'Logística (Despacho y Remito)'), ('remitada', 'Entregada en sitio'), ('solicitud_servicio', 'Solicitud de Servicio'), ('cotizado', 'Servicio Cotizado'), ('permisos_pna', 'Permisos PNA Gestionados'), ('en_ejecucion', 'En Ejecución'), ('reporte_firmado', 'Reporte Firmado / Finalizado'), ('entregada', 'Completada / Cerrada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=50, protected=True),
        ),
    ]
