# Generated by Django 5.0.3 on 2026-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0020_alter_documentoadjunto_tipo_alter_operacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='herramientas_solicitud_particular',
            field=models.TextField(blank=True, help_text='Listado de herramientas a subir/bajar para la Solicitud Particular.', null=True),
        ),
    ]
