# Generated by Django 5.0.3 on 2026-06-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_operacion_herramientas_solicitud_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='solicitud_particular_file',
            field=models.FileField(blank=True, null=True, upload_to='solicitud_particular/'),
        ),
    ]
