# Generated by Django 5.0.3 on 2026-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0022_operacion_solicitud_particular_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='texto_cotizacion_adicional',
            field=models.TextField(blank=True, help_text='Texto adicional o condiciones para la Cotización.', null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='texto_permiso_pna',
            field=models.TextField(blank=True, help_text='Texto personalizado para el PDF de Permiso PNA.', null=True),
        ),
    ]
