# Generated by Django 5.0.3 on 2026-07-08 00:06

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0023_operacion_texto_cotizacion_adicional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='dificil_conseguir',
            field=models.BooleanField(default=False, help_text='Excluye a esta operación de las alertas de tiempo de cotización'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='quotation_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='quoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('recibida', 'Recibida'), ('cotizacion_enviada', 'Cotización Enviada'), ('solicitada', 'Preparación'), ('armado_packing', 'En Gestión (Armado del Packing List)'), ('en_aduana', 'En Aduana (Esperando Rancho)'), ('lista_para_envio', 'Logística (Despacho y Remito)'), ('remitada', 'Entregada en sitio'), ('solicitud_servicio', 'Solicitud de Servicio'), ('cotizado', 'Servicio Cotizado'), ('permisos_pna', 'Permisos PNA Gestionados'), ('en_ejecucion', 'En Ejecución'), ('reporte_firmado', 'Reporte Firmado / Finalizado'), ('entregada', 'Completada / Cerrada'), ('cancelada', 'Cancelada')], default='recibida', max_length=50, protected=True),
        ),
    ]
