# Generated by Django 5.0.3 on 2026-07-08 00:27

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0024_operacion_closed_by_operacion_dificil_conseguir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la que se rechazó la cotización o se pausó la operación', null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=django_fsm.FSMField(choices=[('recibida', 'Recibida'), ('cotizacion_enviada', 'Cotización Enviada'), ('solicitada', 'Preparación'), ('armado_packing', 'En Gestión (Armado del Packing List)'), ('en_aduana', 'En Aduana (Esperando Rancho)'), ('lista_para_envio', 'Logística (Despacho y Remito)'), ('remitada', 'Entregada en sitio'), ('solicitud_servicio', 'Solicitud de Servicio'), ('cotizado', 'Servicio Cotizado'), ('permisos_pna', 'Permisos PNA Gestionados'), ('en_ejecucion', 'En Ejecución'), ('reporte_firmado', 'Reporte Firmado / Finalizado'), ('entregada', 'Completada / Cerrada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada (Rechazada / En Revisión)')], default='recibida', max_length=50, protected=True),
        ),
    ]
