# Generated by Django 5.0.3 on 2026-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0025_operacion_motivo_rechazo_alter_operacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='valor_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetario del trabajo a realizar', max_digits=12, null=True),
        ),
    ]
