# Generated by Django 5.0.3 on 2026-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0026_operacion_valor_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='factura_file',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
