# Generated by Django 5.0.3 on 2026-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0027_operacion_factura_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='lista_ingredientes_file',
            field=models.FileField(blank=True, null=True, upload_to='lista_ingredientes/'),
        ),
    ]
