# Generated by Django 5.0.3 on 2026-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0028_operacion_lista_ingredientes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='reporte_file',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
