# Generated by Django 5.0.3 on 2026-09-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_operacion_reporte_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='detalle_lugar_entrega',
            field=models.CharField(blank=True, help_text='Información adicional sobre el lugar de entrega', max_length=255, null=True),
        ),
    ]
