# Generated by Django 5.0.3 on 2026-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0030_operacion_detalle_lugar_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciondetalle',
            name='forma_cotizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
