# Generated by Django 5.0.3 on 2026-09-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0031_operaciondetalle_forma_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='items_cotizacion_servicio',
            field=models.JSONField(blank=True, default=list, help_text='Items estructurados de servicio para cotizacion', null=True),
        ),
    ]
