# Generated by Django 5.0.3 on 2026-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0032_operacion_items_cotizacion_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='materiales_a_bordo',
            field=models.BooleanField(default=False, help_text='Indica si se dejarán materiales a bordo en un servicio'),
        ),
    ]
