# Generated by Django 5.0.3 on 2026-09-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0033_operacion_materiales_a_bordo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRechazoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Texto del motivo de rechazo de cotización', max_length=255, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
