# Generated by Django 5.0.3 on 2026-09-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0034_motivorechazocatalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='estado_anterior',
            field=models.CharField(blank=True, help_text='Estado previo a la cancelación', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Oculta la operación de la interfaz'),
        ),
    ]
