# Generated by Django 5.0.3 on 2026-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_owner_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dueño / Admin'), ('OPERADOR', 'Operador Administrativo'), ('CONTABLE', 'Contable'), ('OPERARIO', 'Operario de Planta')], default='OPERARIO', max_length=20),
        ),
    ]
