# Generated by Django 5.0.3 on 2026-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_feedbackitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPlantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(help_text='Ej: Operario, Capataz, Especialista', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal de Plantel',
                'verbose_name_plural': 'Personal de Plantel',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
