# Generated by Django 5.0.3 on 2026-06-01 23:23

from django.db import migrations, models


def set_existing_users_false(apps, schema_editor):
    User = apps.get_model('usuarios', 'User')
    User.objects.all().update(must_change_password=False)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_personalplantel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_users_false),
    ]
