# Generated by Django 5.0.3 on 2026-04-01 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('price_list', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('presentation', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo', models.CharField(max_length=7, unique=True)),
                ('flag', models.CharField(max_length=50)),
                ('call_sign', models.CharField(blank=True, max_length=20)),
                ('gross_tonnage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('price_checked', 'Precio verificado'), ('confirmed', 'Confirmada por cliente'), ('in_coordination', 'En coordinación'), ('delivered', 'Entregada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(choices=[('muelle', 'Muelle'), ('lancha', 'Lancha')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('packing_list_file', models.FileField(blank=True, null=True, upload_to='docs/packing/')),
                ('remito_file', models.FileField(blank=True, null=True, upload_to='docs/remito/')),
                ('order_received_date', models.DateTimeField(auto_now_add=True)),
                ('client_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.ship')),
            ],
        ),
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='operations.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.product')),
            ],
            options={
                'unique_together': {('operation', 'product')},
            },
        ),
    ]
