# Generated by Django 5.0.3 on 2026-04-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_agency_client_port_product_ship_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='rancho_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/rancho/'),
        ),
    ]
