# Generated by Django 5.0.3 on 2026-04-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('articulo_final_id', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo_id', models.IntegerField()),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=15)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produccion.formulabom')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_id', models.IntegerField()),
                ('cantidad_a_producir', models.DecimalField(decimal_places=2, max_digits=15)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produccion.formulabom')),
            ],
        ),
    ]
