# Generated by Django 5.0.3 on 2026-04-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('presentacion', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('stock_resultante', models.DecimalField(decimal_places=4, max_digits=15)),
                ('operacion_id', models.IntegerField(blank=True, null=True)),
                ('razon', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.articulo')),
            ],
        ),
    ]
