# Generated by Django 5.0.3 on 2026-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('quimicos', 'Químicos'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
