# Generated by Django 5.0.3 on 2026-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Stock mínimo para alerta (amarillo)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
