# Generated by Django 5.0.3 on 2026-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_articulo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('30_dias', '30 Días'), ('60_dias', '60 Días'), ('90_dias', '90 Días'), ('otros', 'Otros')], default='contado', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
