# Generated by Django 5.0.3 on 2026-05-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_articulo_id_alter_movimientostock_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Stock máximo (opcional)', max_digits=15),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('campos_modificados', models.JSONField(blank=True, default=dict, help_text='Diccionario de campos y valores antiguos/nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventario.articulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Producto',
                'verbose_name_plural': 'Logs de Productos',
                'ordering': ['-fecha'],
            },
        ),
    ]
