# Generated by Django 5.0.3 on 2026-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientostock_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='controlar_stock',
            field=models.BooleanField(default=True, help_text='Si se desmarca, el artículo no requerirá stock en inventario y no bloqueará confirmaciones.'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('quimicos', 'Químicos'), ('otros', 'Otros'), ('insumos', 'Insumos')], default='otros', max_length=20),
        ),
    ]
