# Generated by Django 5.0.3 on 2026-06-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_articulo_controlar_stock_alter_articulo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Anclas', 'Anclas'), ('Cadenas', 'Cadenas'), ('Químicos', 'Químicos'), ('Herramientas', 'Herramientas'), ('Patio', 'Patio')], max_length=20)),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros'), ('u', 'Unidades'), ('m', 'Metros'), ('par', 'Pares')], max_length=5)),
                ('ubicacion', models.CharField(choices=[('Patio A', 'Patio A'), ('Patio B', 'Patio B'), ('Oficina sup.', 'Oficina sup.'), ('Planta baja', 'Planta baja'), ('Químicos', 'Químicos')], max_length=30)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Oxidado', 'Oxidado'), ('Caducado', 'Caducado')], max_length=10)),
                ('serie_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
