# Generated by Django 5.0.3 on 2026-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado del producto (Nuevo, Usado, Oxidado, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='serie_lote',
            field=models.CharField(blank=True, help_text='Número de serie o lote', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física del producto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad',
            field=models.CharField(blank=True, help_text='Unidad de medida (kg, L, u, m, par)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Observaciones o descripción del producto'),
        ),
    ]
