# Generated by Django 5.0.3 on 2026-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_articulo_estado_articulo_serie_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('quimicos', 'Químicos'), ('anclas', 'Anclas'), ('otros', 'Otros'), ('insumos', 'Insumos')], default='otros', max_length=20),
        ),
    ]
