# Generated by Django 5.0.3 on 2026-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Costo unitario (manual o calculado)', max_digits=15),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Precio de venta unitario', max_digits=15),
        ),
    ]
