# Generated by Django 5.0.3 on 2026-07-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_articulo_costo_articulo_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
