# Generated by Django 5.0.3 on 2026-08-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='categoria',
            field=models.CharField(choices=[('Anclas', 'Anclas'), ('Cadenas', 'Cadenas'), ('Químicos', 'Químicos'), ('Empaque', 'Empaque'), ('Herramientas', 'Herramientas'), ('Patio', 'Patio')], max_length=20),
        ),
    ]
