# Generated by Django 5.0.3 on 2026-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_stockitem_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Nombre en inglés', max_length=200, null=True),
        ),
    ]
